version: '3'

services:

  app:
    image: 'tmvdl/projects:percent'
    build: './src/app'
    volumes:
      - './src/app:/app'
      - './data:/data'
    environment:
      - 'PORT=80'
      - 'DATA_PATH=/data'
    ports:
      - '8080:80'

  git:
    image: 'git'
    build: './src/git'
    ports:
      - '2020:22'

  release:
    image: 'release'
    build: './src'

  github-release:
    image: 'github-release'
    build: './src'

  www:
    image: 'tmvdl/projects:apply'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'
    depends_on:
      - 'api'
