version: '3'

services:

  app:
    image: 'tmvdl/projects:percent'
    build: './src/app'
    volumes:
      - './src/app:/app'
      - './data:/data'
    environment:
      - 'PORT=80'
      - 'DATA_PATH=/data'
    ports:
      - '8080:80'

  release:
    image: 'release'
    build: './src'

  github-release:
    image: 'github-release'
    build: './src'
